## 1. Import Necessary Package

In [1]:
!pip install stable-baselines[mpi]==2.10.0
import gym
import numpy as np
import time
import os
import matplotlib.pyplot as plt
import math

from simple_particle import SimpleParticle # Importing Environment
from stable_baselines.common.env_checker import check_env


/home/cmb/anaconda3/envs/microrobot/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/cmb/anaconda3/envs/microrobot/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/cmb/anaconda3/envs/microrobot/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/cmb/anaconda3/envs/microrobot/lib/pyt

In [2]:

from stable_baselines.common.policies import MlpPolicy
from stable_baselines.deepq.policies import FeedForwardPolicy
from stable_baselines import DQN, PPO2, A2C, ACKTR
from stable_baselines.bench import Monitor
from stable_baselines.common.vec_env import DummyVecEnv
from stable_baselines.results_plotter import load_results, ts2xy
from stable_baselines.common.noise import AdaptiveParamNoiseSpec, NormalActionNoise
%matplotlib inline

## 2. Instantiating the Environment

In [3]:
# Setting Parameters 
# numParticles, phi, stateBounds, dwellTime, maxSteps
numParticles = 1
phi = 0 

env = SimpleParticle(numParticles = numParticles, 
               phi = phi, 
               stateBounds = [-10.0, 10.0, -5.0, 5.0],
               dwellTime = 1.0, 
               maxSteps = 25)


/home/cmb/anaconda3/envs/microrobot/lib/python3.6/site-packages/gym/logger.py:30: UserWarning: WARN: Box bound precision lowered by casting to float32
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))


## 3. Checking the Environment

In [4]:
# Check the environment
env_test = SimpleParticle(numParticles = numParticles, 
               phi = phi, 
               stateBounds = [-10.0, 10.0, -5.0, 5.0],
               dwellTime = 1.0, 
               maxSteps = 25)

# Check
check_env(env_test, warn=True)

[ 1.69200109 -3.39321911 -0.01937325 -0.89710891]


## 4. Instantiate the Agent

In [5]:
# Custom MLP Policy 
policy_kwargs = dict(net_arch=[256, 256])

# Define the model
model = PPO2('MlpPolicy', env, n_steps = 256, policy_kwargs=policy_kwargs, verbose=1)

Wrapping the env in a DummyVecEnv.




Instructions for updating:
Use keras.layers.flatten instead.


Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where




# Callback

In [6]:
best_mean_reward = -np.inf
n_steps = 0

num_episodes = 500

def callback(_locals, _globals):
    """
    Callback is called at each step (timestep) for DQN
    :param_locals: (dict)
    :param_globals: (dict)
    """
    global n_steps, best_mean_reward
    
    if (env.episode) > num_episodes:
        return False
    
    # Returning false will stop training early
    return True

In [7]:
# Create log dir
log_dir = "/tmp/gym/"
os.makedirs(log_dir, exist_ok=True)

# Train the agent
model.learn(total_timesteps=int(1e100), callback=callback)

[-0.10870803  0.73673041  0.3456793   0.08752392]
[-2.5691147   2.08986565 -0.94002356  0.81783611]
[3.9009383  2.58548999 0.56647084 0.94981429]
[-1.36829594 -0.20702352  0.69467463  0.96550307]
[ 1.49762016  1.18007839 -0.45948829  0.37635416]
[-1.63506515  3.56199713  0.53509806  0.80679499]
[ 2.71176191 -3.04542966 -0.67842948  0.14933962]
[ 0.29648745 -3.62740408 -0.90142194  0.57793793]
[ 0.62331251  1.13607756 -0.71115624 -0.20482282]
[-0.90977718 -3.24489785 -0.88838044 -0.30076506]
[ 2.06925079 -0.00621856  0.62387045 -0.35587109]
---------------------------------------
| approxkl           | 2.3833259e-06  |
| clipfrac           | 0.0            |
| explained_variance | -1.1e-05       |
| fps                | 37             |
| n_updates          | 1              |
| policy_entropy     | 1.3862828      |
| policy_loss        | -0.00037735802 |
| serial_timesteps   | 256            |
| time_elapsed       | 2.29e-05       |
| total_timesteps    | 256            |
| value_loss  

[-3.20097577 -2.01524333 -0.13935965  0.34018209]
[ 0.12066976  1.51842438  0.42640219 -0.87808751]
[ 2.7028224  -1.3865415  -0.5570609   0.60810863]
[0.62936555 0.14712184 0.92031749 0.60376005]
[ 2.51906354 -0.20948994 -0.70064396  0.42730604]
[-1.11848787 -3.44173215 -0.26473442  0.1658791 ]
[ 2.89178163 -1.61137354 -0.37921255 -0.12235733]
[ 3.1441759   2.82734827 -0.01930689  0.06638643]
[-0.9702244  -3.11234822  0.33136089  0.89897788]
[-3.05126008  2.26575662  0.20061897 -0.61551629]
[ 3.23351775  2.3698304   0.93008688 -0.16446293]
--------------------------------------
| approxkl           | 4.5224686e-05 |
| clipfrac           | 0.0           |
| explained_variance | 9.88e-05      |
| fps                | 1961          |
| n_updates          | 9             |
| policy_entropy     | 1.3833063     |
| policy_loss        | -0.002145039  |
| serial_timesteps   | 2304          |
| time_elapsed       | 7.66          |
| total_timesteps    | 2304          |
| value_loss         | 29

[-3.52738006  1.45032537 -0.45980853  0.84519512]
[ 3.39462631  0.7168269  -0.09739475  0.56971561]
[-3.50275531e+00  2.24810699e-03 -9.74249963e-01 -4.69305732e-01]
[ 1.58808555  1.12158185 -0.61519858  0.14215642]
[ 3.43985363 -2.63045533  0.35336918  0.87856788]
[ 3.33363282  1.5835495   0.20434819 -0.53995207]
[ 0.19237588 -0.50486953  0.10258311  0.22666742]
[-3.60147452  0.77727009 -0.81994492 -0.96782768]
[ 1.70315869 -3.16054119 -0.58329291  0.38706129]
[ 3.83268727 -1.27752599 -0.25962309  0.37534936]
[ 0.53216078 -2.18318038  0.78284166 -0.39294277]
---------------------------------------
| approxkl           | 4.828572e-06   |
| clipfrac           | 0.0            |
| explained_variance | 0.000229       |
| fps                | 1943           |
| n_updates          | 17             |
| policy_entropy     | 1.3729125      |
| policy_loss        | -0.00011114695 |
| serial_timesteps   | 4352           |
| time_elapsed       | 8.71           |
| total_timesteps    | 4352       

[-5.29896735e-01  3.68488851e+00 -2.04490291e-03 -9.97790977e-01]
[0.76398757 1.48180843 0.93900477 0.90509718]
[-1.42749023  3.19566571 -0.39081647 -0.66583915]
[0.18017469 1.58457534 0.96158309 0.22407252]
[ 0.41734995  0.27517018 -0.35951235 -0.75771405]
[ 2.29933174 -0.53309104  0.99106115 -0.00683625]
[-3.93954038  3.7850343   0.9050957  -0.32858188]
[ 3.4376013  -0.36014301  0.75591642 -0.05839148]
[-1.56450084 -2.78028359 -0.99569078  0.85685514]
[0.05952559 2.63268994 0.52657791 0.51977833]
[ 2.89561219 -1.96454075 -0.26005136  0.90422802]
--------------------------------------
| approxkl           | 0.00011274058 |
| clipfrac           | 0.0           |
| explained_variance | -6.23e-05     |
| fps                | 1909          |
| n_updates          | 25            |
| policy_entropy     | 1.3500617     |
| policy_loss        | 0.0014904502  |
| serial_timesteps   | 6400          |
| time_elapsed       | 9.78          |
| total_timesteps    | 6400          |
| value_loss     

[ 1.56658903  0.10855199 -0.13923078 -0.10386415]
[-0.43771412 -1.73228176 -0.00614303 -0.0639462 ]
[-2.37338885  1.74171967  0.64950029  0.52409733]
[ 3.19692708 -2.0332988  -0.99075656 -0.41357006]
[-3.40645815  1.15253532  0.76067788 -0.2635807 ]
[ 3.200043   -3.76209983  0.09970246  0.61537681]
[-2.88176246 -1.734571    0.97243474 -0.66976548]
[-3.13952189 -0.75097831  0.63777344 -0.53441292]
[ 3.48884543 -0.1646621   0.92261292  0.75545099]
[ 0.0243146  -2.01844186  0.46151532 -0.90073147]
--------------------------------------
| approxkl           | 0.0007673404  |
| clipfrac           | 0.0           |
| explained_variance | -5.95e-05     |
| fps                | 1851          |
| n_updates          | 33            |
| policy_entropy     | 1.1915874     |
| policy_loss        | -0.0012703055 |
| serial_timesteps   | 8448          |
| time_elapsed       | 10.9          |
| total_timesteps    | 8448          |
| value_loss         | 2279688.5     |
--------------------------------

[-3.53957479  0.30556204  0.61878032  0.54442836]
[-0.29893355 -1.15436111 -0.73819024  0.22509831]
[ 2.13636486  3.56692711  0.41477405 -0.2872063 ]
[ 3.16163934 -2.33449877 -0.29421866 -0.60986608]
[ 0.00319263  2.13196861 -0.66627737  0.77747558]
[ 2.74509698  1.55632633 -0.74721217 -0.75766465]
[-2.53205934  2.58824355 -0.84283294  0.38588486]
[ 1.96127186  3.12478618  0.73025273 -0.63800016]
[ 3.88990977 -3.09046942 -0.74729537  0.51787567]
[-3.27661047  1.87568161  0.13499596 -0.83553651]
--------------------------------------
| approxkl           | 0.0004638206  |
| clipfrac           | 0.0           |
| explained_variance | -0.000104     |
| fps                | 1912          |
| n_updates          | 41            |
| policy_entropy     | 1.1216339     |
| policy_loss        | -0.0021917524 |
| serial_timesteps   | 10496         |
| time_elapsed       | 12            |
| total_timesteps    | 10496         |
| value_loss         | 827086.8      |
--------------------------------

[-0.32105882  1.40591098  0.13686598  0.58888427]
[-1.82370112  2.66690422 -0.96650634  0.51014436]
[-1.94735661 -3.57933363 -0.78651562  0.1368559 ]
[ 1.39707774  1.80291706 -0.147873    0.89884818]
[ 0.41216802 -1.24698067 -0.1177292  -0.48984612]
[-2.44429166 -3.8446694  -0.60440671 -0.57314456]
[-0.51424388 -0.45828496  0.78993916 -0.95255036]
[ 3.36682687  1.50083682 -0.3831505  -0.25434388]
[ 0.20030024  1.15460717 -0.27462288  0.86800111]
[ 1.67179602 -2.14139897  0.2031819   0.91642895]
-------------------------------------
| approxkl           | 0.0055784527 |
| clipfrac           | 0.076171875  |
| explained_variance | -0.000125    |
| fps                | 1935         |
| n_updates          | 49           |
| policy_entropy     | 1.063429     |
| policy_loss        | 0.016404098  |
| serial_timesteps   | 12544        |
| time_elapsed       | 13           |
| total_timesteps    | 12544        |
| value_loss         | 7067178.0    |
-------------------------------------
[-3.87

[ 1.44751896  0.12084337 -0.44187176  0.14810978]
[ 3.01503823 -3.67853862 -0.72575061 -0.4353116 ]
[ 3.02773334 -0.24420963  0.79251807  0.26697774]
[0.77962093 2.58032605 0.95906928 0.09401432]
[-1.47470465  0.99297186 -0.65908922 -0.78212305]
[ 2.33124955  0.03750305 -0.84270445 -0.69053015]
[-2.26699262 -3.95403636 -0.64777936 -0.14745821]
[ 3.30637529 -0.22446254  0.79858877  0.57836429]
[-3.20097238  1.35760503 -0.15216594 -0.39444712]
[ 2.88200821 -0.5885285   0.26267012  0.28691945]
--------------------------------------
| approxkl           | 0.0015052427  |
| clipfrac           | 0.0           |
| explained_variance | -0.000318     |
| fps                | 1929          |
| n_updates          | 57            |
| policy_entropy     | 0.8889671     |
| policy_loss        | -0.0035934479 |
| serial_timesteps   | 14592         |
| time_elapsed       | 14.1          |
| total_timesteps    | 14592         |
| value_loss         | 4552788.5     |
------------------------------------

[-2.61123839 -3.29741713 -0.52731959 -0.27120588]
[1.28838262 0.87389136 0.21741904 0.65800626]
[-0.94421305 -3.2903451  -0.03454365  0.00743343]
[ 2.31391622  3.39834851 -0.05918353  0.23111111]
[-0.67054475 -1.49278768 -0.26114562 -0.72835234]
[ 1.69737544 -3.16921551 -0.63362946 -0.34316377]
[ 0.33085835 -0.38913187 -0.63195868  0.16337596]
[ 3.79352593  0.99209164  0.56467704 -0.49104723]
[-0.76180207  1.68394659 -0.16085908  0.93885314]
[ 2.77525123 -3.17705472 -0.6950144   0.51150319]
-------------------------------------
| approxkl           | 0.0019568242 |
| clipfrac           | 0.0          |
| explained_variance | -0.000178    |
| fps                | 2000         |
| n_updates          | 65           |
| policy_entropy     | 0.8035181    |
| policy_loss        | 0.0007711395 |
| serial_timesteps   | 16640        |
| time_elapsed       | 15.2         |
| total_timesteps    | 16640        |
| value_loss         | 3212574.2    |
-------------------------------------
[ 1.147014

[-1.47836466  0.17272323 -0.07708024 -0.85746655]
[ 0.03159484 -3.71966292  0.52145088 -0.09143932]
[ 1.18696056  1.95376965 -0.82214954 -0.14010518]
[-1.82393278  0.75113376  0.59008285  0.81776638]
[0.85719107 1.65406497 0.96033747 0.17589475]
[-1.24491591  0.68084808  0.24953051  0.02299728]
[-1.56617868  0.00663434 -0.00232     0.78759625]
[-2.6121383   1.31692373  0.54614074  0.30898281]
[ 0.47223924  1.15122628 -0.47084083  0.01099198]
[3.6536772  3.88905537 0.40534747 0.24561585]
-------------------------------------
| approxkl           | 0.0033588726 |
| clipfrac           | 0.0          |
| explained_variance | -0.000176    |
| fps                | 1856         |
| n_updates          | 73           |
| policy_entropy     | 0.8038761    |
| policy_loss        | 0.0068959454 |
| serial_timesteps   | 18688        |
| time_elapsed       | 16.2         |
| total_timesteps    | 18688        |
| value_loss         | 8896170.0    |
-------------------------------------
[-0.54802493  

[-3.8796636  -3.58401946 -0.84032675 -0.62287766]
[ 2.47061621  3.2080908  -0.99139527 -0.17962272]
[-0.9889652   3.98177945  0.79377089  0.23970374]
[ 2.79896253  1.3322496  -0.07006939  0.36955735]
[-0.28556229 -3.56248462 -0.97103435  0.61026314]
[-2.7326584  -3.08638454  0.91381482  0.79305155]
[-1.84377173 -2.93006748  0.52194366 -0.49230742]
[ 2.19125454  0.68191864 -0.29585654  0.39717139]
[3.35317646 1.98036925 0.80997183 0.79576538]
[-1.04706498 -0.14317518  0.43114724  0.43427279]
--------------------------------------
| approxkl           | 0.0010798275  |
| clipfrac           | 0.0029296875  |
| explained_variance | 7.87e-05      |
| fps                | 1997          |
| n_updates          | 81            |
| policy_entropy     | 0.7670158     |
| policy_loss        | -0.0005356673 |
| serial_timesteps   | 20736         |
| time_elapsed       | 17.3          |
| total_timesteps    | 20736         |
| value_loss         | 2076098.1     |
------------------------------------

[ 3.50726806  1.83476551 -0.03763451  0.01962437]
[ 1.89276691  3.13201548 -0.76334666  0.63756495]
[-2.43846798 -1.80761928  0.49844617 -0.03596691]
[ 1.82422923  1.26094647  0.4647676  -0.61278546]
[-3.24820702  3.2444761  -0.45023617 -0.60611475]
[-0.12904699 -1.4709124   0.20431035 -0.80903937]
[ 2.85139296  2.25466798 -0.27861352 -0.95464118]
[ 1.33200029  0.7963702   0.31525971 -0.21345883]
[ 2.48875837 -3.84516266  0.40074501 -0.88734435]
[ 2.76093687  2.46581084 -0.10351235  0.3766535 ]
--------------------------------------
| approxkl           | 0.00056981714 |
| clipfrac           | 0.0           |
| explained_variance | -0.00041      |
| fps                | 1957          |
| n_updates          | 89            |
| policy_entropy     | 0.77676374    |
| policy_loss        | 0.0058273226  |
| serial_timesteps   | 22784         |
| time_elapsed       | 18.3          |
| total_timesteps    | 22784         |
| value_loss         | 5679978.0     |
--------------------------------

[ 2.55063065 -2.91710674 -0.24919212  0.81561522]
[-3.05518416  2.37481378 -0.69369456  0.04718878]
[-3.94158264  3.47412596  0.36671693  0.3250743 ]
[ 1.58509056 -1.41194941 -0.98715425  0.73253466]
[-1.81646286 -0.92815626 -0.38035487  0.87221039]
[ 0.20494535 -3.37147235 -0.13608698  0.66281139]
[-2.13576454  3.32568063  0.92000883  0.47850487]
[ 1.37213282 -3.47943527  0.19902634  0.33401785]
[ 1.28652645 -3.39210426 -0.10821786 -0.14025946]
[ 3.04221077 -1.57277701 -0.50099503 -0.65473102]
-------------------------------------
| approxkl           | 0.0036318921 |
| clipfrac           | 0.00390625   |
| explained_variance | -0.000131    |
| fps                | 2033         |
| n_updates          | 97           |
| policy_entropy     | 0.78454864   |
| policy_loss        | -0.020784754 |
| serial_timesteps   | 24832        |
| time_elapsed       | 19.4         |
| total_timesteps    | 24832        |
| value_loss         | 14939254.0   |
-------------------------------------
[ 0.61

[-0.94798111 -2.50876454  0.19981021  0.86247782]
[-3.92897336e+00  3.28921704e+00 -3.34429001e-03 -8.23987277e-02]
[-2.23326762  3.78543827  0.8266593  -0.21390907]
[ 1.01377432  2.41079373 -0.41075973 -0.36213259]
[-2.06984672 -0.80958399  0.3729407   0.93085447]
[-0.55417474  1.95727394  0.62520955  0.62549856]
[-1.32790174 -2.91235304 -0.23282287  0.41703515]
[-1.36868277 -2.37174055 -0.09822626  0.1689906 ]
[-3.09666704  0.84234754  0.05302977  0.11018577]
[-3.35020645  1.7417983  -0.35893854  0.15259051]
[-3.66802408 -2.05892181  0.06804144  0.5194845 ]
------------------------------------
| approxkl           | 0.019452743 |
| clipfrac           | 0.40234375  |
| explained_variance | -3.14e-05   |
| fps                | 1903        |
| n_updates          | 105         |
| policy_entropy     | 0.74871314  |
| policy_loss        | 0.038519956 |
| serial_timesteps   | 26880       |
| time_elapsed       | 20.5        |
| total_timesteps    | 26880       |
| value_loss         | 7838

[-3.03846428  3.7752214  -0.94726473 -0.36322602]
[-0.10372562 -2.1448298   0.58062778  0.9101244 ]
[ 0.63005196 -2.56671969 -0.1091721   0.99673655]
[-2.52412917  2.29037948 -0.20117895  0.22246749]
[-3.98132003 -0.08114253 -0.45873362  0.27696278]
[-3.70783293  3.05390856  0.96517154 -0.22905926]
[ 3.64235688  2.64801127  0.87133688 -0.11170979]
[-1.95506958  3.29074625 -0.99592599  0.63433893]
[-1.40293198  2.9364051  -0.40069143  0.60302279]
[-2.83125414 -0.55122086 -0.49559332  0.82423653]
[-0.17863117  2.0738935  -0.30368188  0.09612095]
--------------------------------------
| approxkl           | 0.00011596195 |
| clipfrac           | 0.0           |
| explained_variance | -7.14e-05     |
| fps                | 1946          |
| n_updates          | 113           |
| policy_entropy     | 0.73626363    |
| policy_loss        | 0.0008506124  |
| serial_timesteps   | 28928         |
| time_elapsed       | 21.5          |
| total_timesteps    | 28928         |
| value_loss         

[-0.36298028 -3.88733271  0.41428776 -0.6773502 ]
[-0.07770196  1.61941033 -0.05542561 -0.57732384]
[ 2.85023502  2.6926156  -0.78976756  0.24479756]
[-3.10362413 -2.19894005 -0.19765064 -0.03300793]
[-2.55169842 -0.67507344  0.22867342  0.93308665]
[-1.85839017 -3.5968221  -0.38825554 -0.62703642]
[ 0.2309452   1.20124794 -0.07099078 -0.88121442]
[-3.41520745  2.63078989 -0.01315332 -0.23096221]
[ 3.47996185  2.0832455  -0.63630768  0.89919217]
[-0.27727728  1.33140318 -0.79505556  0.32103837]
[ 1.01075075 -1.80389066 -0.42607867 -0.23610445]
------------------------------------
| approxkl           | 0.002627908 |
| clipfrac           | 0.0         |
| explained_variance | 6.29e-05    |
| fps                | 1930        |
| n_updates          | 121         |
| policy_entropy     | 0.7481776   |
| policy_loss        | 0.010381854 |
| serial_timesteps   | 30976       |
| time_elapsed       | 22.6        |
| total_timesteps    | 30976       |
| value_loss         | 11239474.0  |
------

[-0.89742114 -2.44410332 -0.04354064  0.76041527]
[-0.5587437   2.88472633  0.23312565 -0.89096957]
[-1.4092338   2.11230541 -0.2070002  -0.6478165 ]
[ 3.46640316 -0.15077177 -0.68360653  0.54076571]
[-0.95579751 -1.00302461 -0.99401651 -0.49825856]
[ 2.4777773  -2.03340614  0.18529094 -0.10737644]
[ 0.20669738  1.11747654 -0.30897803 -0.57751799]
Episode 34	Average Score: -326091.50[ 2.42579824 -1.04464206  0.54651288 -0.26370175]
-------------------------------------
| approxkl           | 0.0031414519 |
| clipfrac           | 0.0          |
| explained_variance | -1.28e-05    |
| fps                | 1900         |
| n_updates          | 129          |
| policy_entropy     | 0.7441767    |
| policy_loss        | 0.0009134652 |
| serial_timesteps   | 33024        |
| time_elapsed       | 23.6         |
| total_timesteps    | 33024        |
| value_loss         | 4134192.8    |
-------------------------------------
[-1.43302952  1.76975375  0.86434433 -0.22347543]
[ 3.74053411  2.1229

[ 1.31356894  0.31857851 -0.16803864 -0.23344688]
[-3.21648968  0.00907756 -0.17297777 -0.74471661]
[-3.83510515 -0.96601675 -0.72637749 -0.55005685]
[-3.50945622 -0.15413054  0.38191811 -0.83126555]
[ 0.55127884 -2.61210026  0.36416515  0.27889355]
[ 3.99682987 -3.34611833 -0.11790944 -0.04064113]
Episode 36	Average Score: -320809.60[ 3.45606658 -1.12880967  0.71432751  0.66157657]
[ 2.65297196 -3.93315166  0.42518168 -0.63339168]
[-1.24236294 -1.69609659 -0.59741872  0.72103602]
------------------------------------
| approxkl           | 0.000571005 |
| clipfrac           | 0.0         |
| explained_variance | -8.8e-05    |
| fps                | 2006        |
| n_updates          | 137         |
| policy_entropy     | 0.7455303   |
| policy_loss        | 0.004426645 |
| serial_timesteps   | 35072       |
| time_elapsed       | 24.6        |
| total_timesteps    | 35072       |
| value_loss         | 7122677.0   |
------------------------------------
[-0.96220141  3.42042342  0.82971

[-3.81264582  2.27644364 -0.75856084  0.57190273]
[ 2.80317939  1.15447188 -0.46782401  0.58279968]
[-0.68736272  3.19929681 -0.38057988 -0.35706872]
[-0.7098993   3.30680082 -0.78521592 -0.74679783]
Episode 38	Average Score: -318341.16[ 1.42283044 -1.52750158  0.15293006  0.4451797 ]
[ 1.16484558 -1.40578351 -0.34438182  0.69533411]
[-1.87974536  3.07775573 -0.35704018 -0.19972558]
[-3.75091295 -2.46266413  0.35317292 -0.73616633]
[ 0.62065503 -1.50999388  0.28243057  0.68842207]
--------------------------------------
| approxkl           | 0.000529622   |
| clipfrac           | 0.0           |
| explained_variance | -8.98e-05     |
| fps                | 1972          |
| n_updates          | 145           |
| policy_entropy     | 0.7259398     |
| policy_loss        | -0.0031291265 |
| serial_timesteps   | 37120         |
| time_elapsed       | 25.7          |
| total_timesteps    | 37120         |
| value_loss         | 8776951.0     |
--------------------------------------
[ 2.211

[ 1.85256309  2.18681441 -0.3975912   0.99523776]
[0.15126634 0.36606224 0.67863921 0.46498524]
[-1.669655    0.32644984 -0.65666653  0.09183302]
Episode 40	Average Score: -316541.53
[-2.47682155  2.3111605  -0.22969997 -0.50043534]
[-0.23911387 -2.66890093  0.23452734  0.05416643]
[-0.3205316  -3.68681386  0.15019552 -0.83992891]
[ 2.26762857  0.82281254 -0.02916903  0.40096916]
[ 0.52063938  0.94706629 -0.6503159   0.42410434]
[-0.21205421  0.80280553  0.69706482  0.59663339]
[ 0.93824793 -2.14195333  0.89280319  0.04312575]
--------------------------------------
| approxkl           | 0.00028094003 |
| clipfrac           | 0.0           |
| explained_variance | -2.75e-05     |
| fps                | 1953          |
| n_updates          | 153           |
| policy_entropy     | 0.71594805    |
| policy_loss        | -0.0025843638 |
| serial_timesteps   | 39168         |
| time_elapsed       | 26.8          |
| total_timesteps    | 39168         |
| value_loss         | 11695496.0    |

[-1.6521873  -2.33529495 -0.62253011  0.47048872]
Episode 42	Average Score: -317369.95[1.79700615 2.52256211 0.92777468 0.46424616]
[-0.18722648 -1.96170734  0.43057762  0.47440357]
[ 2.00593918 -2.90807118  0.98496959  0.25870416]
[-0.98235733 -1.3357148  -0.07174044 -0.65494651]
[-1.27608698  3.20540525 -0.7707688   0.94046964]
[-0.97177629  2.49353202 -0.47348888 -0.63648708]
[ 3.31060973  3.99151566 -0.36377741  0.32160616]
[ 0.38517615  2.6921162  -0.3807378   0.30608768]
[-2.5013991  -0.20082666 -0.69449968 -0.09638966]
-------------------------------------
| approxkl           | 0.0004501092 |
| clipfrac           | 0.0          |
| explained_variance | -1.66e-05    |
| fps                | 1733         |
| n_updates          | 161          |
| policy_entropy     | 0.74577826   |
| policy_loss        | 0.0043851105 |
| serial_timesteps   | 41216        |
| time_elapsed       | 27.8         |
| total_timesteps    | 41216        |
| value_loss         | 4852378.5    |
------------

[ 0.82999739  2.45078964 -0.84774121 -0.4727576 ]
[-1.32432667 -2.15212633  0.26949401 -0.72236281]
[-3.02349626 -2.21227457  0.62054912 -0.10930195]
[ 3.46431843  2.25770622 -0.98041295  0.01343112]
[ 1.91319602  1.47488492  0.26521652 -0.4433439 ]
[-2.49569897  0.82633518 -0.15205646 -0.36670296]
[ 0.32881746 -1.46344187  0.66302173 -0.67970216]
[ 0.34608653 -0.35131199  0.76483944  0.00596128]
[ 2.67278673  3.91312494 -0.10897138  0.4718997 ]
[ 1.34913694  3.74984854 -0.1356135  -0.81628209]
-------------------------------------
| approxkl           | 0.0029685958 |
| clipfrac           | 0.0          |
| explained_variance | 6.56e-06     |
| fps                | 1896         |
| n_updates          | 169          |
| policy_entropy     | 0.74286306   |
| policy_loss        | 0.017171074  |
| serial_timesteps   | 43264        |
| time_elapsed       | 28.9         |
| total_timesteps    | 43264        |
| value_loss         | 10962330.0   |
-------------------------------------
[-1.37

[-3.11207066 -3.5187139  -0.39586396 -0.79684561]
[-2.75912911 -1.65773989  0.5727164   0.55973773]
[2.58719457 0.83465818 0.14141186 0.09128593]
[ 1.71142274 -2.62223976  0.81018187 -0.70835146]
[ 2.55517145  1.79128121 -0.25837114  0.84435393]
[-3.02981538 -0.52244166  0.30754173  0.81426765]
[ 1.53108676  0.65141922  0.986776   -0.15320299]
[-0.89425339  2.96503576  0.88096554  0.41938198]
[-1.62010066 -3.00055515  0.28298897  0.47107284]
[-0.41640233  3.16960509  0.8381984   0.32306689]
---------------------------------------
| approxkl           | 6.5413646e-05  |
| clipfrac           | 0.0            |
| explained_variance | -1.18e-05      |
| fps                | 1888           |
| n_updates          | 177            |
| policy_entropy     | 0.70192915     |
| policy_loss        | -0.00022422773 |
| serial_timesteps   | 45312          |
| time_elapsed       | 30             |
| total_timesteps    | 45312          |
| value_loss         | 7081417.0      |
------------------------

[ 1.8876906  -0.17612228  0.52119157  0.40367531]
[-2.54345975  1.38397863  0.75290463 -0.89800849]
[ 1.43771159 -2.68423708 -0.36604221 -0.50281423]
[-1.48886529 -3.37293544  0.71023248 -0.97971579]
[ 0.14854302  1.02827461  0.83187903 -0.12472906]
[ 2.29389576 -0.26476067  0.83352863 -0.48720204]
[-1.5585922   3.77616837 -0.88387583 -0.05812812]
[-1.94097    -2.71144892  0.16395389  0.76254952]
[-1.53899088  2.83799169 -0.34687804 -0.01256794]
[-2.45355124 -1.45657993  0.77394411  0.43094813]
--------------------------------------
| approxkl           | 5.1589657e-05 |
| clipfrac           | 0.0           |
| explained_variance | -2.91e-05     |
| fps                | 1927          |
| n_updates          | 185           |
| policy_entropy     | 0.7148423     |
| policy_loss        | 0.0004928339  |
| serial_timesteps   | 47360         |
| time_elapsed       | 31            |
| total_timesteps    | 47360         |
| value_loss         | 3972767.0     |
--------------------------------

[ 3.49077381 -2.52002032 -0.24242875 -0.17320296]
[-3.89240224  3.80246726 -0.92980663  0.48942573]
[2.77248189 0.82814127 0.97609088 0.75420469]
[-2.54446526  0.73449068 -0.21953031  0.05146591]
[ 3.0105516  -2.37542869  0.92928843  0.28481642]
[-3.42044381  2.872759   -0.9631226   0.38910302]
[ 0.36988105 -0.51794025 -0.37236637  0.5870785 ]
[-1.82806494 -1.4796125  -0.95392593  0.40355192]
[ 1.66208777 -2.70903294  0.55737111 -0.48095894]
[-1.80957373 -2.71767724 -0.75027012  0.51307968]
--------------------------------------
| approxkl           | 0.00040472095 |
| clipfrac           | 0.0           |
| explained_variance | 1.22e-05      |
| fps                | 1966          |
| n_updates          | 193           |
| policy_entropy     | 0.714036      |
| policy_loss        | 0.0008452976  |
| serial_timesteps   | 49408         |
| time_elapsed       | 32.1          |
| total_timesteps    | 49408         |
| value_loss         | 650935.4      |
------------------------------------

[-1.64453613 -0.73627262  0.06753318 -0.56717176]
[ 0.8069063   2.90683141 -0.46882391  0.91458255]
[-1.88203634 -2.96986136 -0.80289043  0.47088221]
[ 1.27759251  2.21196489 -0.03039423 -0.72070964]
[ 1.77052266  1.42259278  0.79961256 -0.57230012]
[-2.28851942  0.31819721 -0.63623803 -0.99281262]
[ 3.86682414 -3.90189074  0.4647997  -0.11061903]
[-0.56762267  0.16226722  0.27191447  0.35532166]
[-2.99415919 -0.2465371  -0.16623556  0.7433936 ]
[-1.92986047 -0.57090883 -0.33628579 -0.50659698]
--------------------------------------
| approxkl           | 0.00014400075 |
| clipfrac           | 0.0           |
| explained_variance | 4.47e-06      |
| fps                | 2011          |
| n_updates          | 201           |
| policy_entropy     | 0.71332395    |
| policy_loss        | -0.0006001198 |
| serial_timesteps   | 51456         |
| time_elapsed       | 33.2          |
| total_timesteps    | 51456         |
| value_loss         | 6916900.0     |
--------------------------------

[ 0.2968214   3.49184036 -0.80345806 -0.76351165]
[3.33593633 2.22953557 0.92702064 0.17268978]
[-1.09293042  2.99831303  0.0512059  -0.17401369]
[ 1.77441252  3.07290908 -0.84659574 -0.53091839]
[ 3.37418009 -2.53342689 -0.90737273  0.74351569]
[-2.02762273  2.07364865  0.9078424   0.45407099]
[-0.63811287  0.43661393 -0.20041078 -0.16891609]
[ 0.74082837 -1.73419982  0.4439045   0.93707366]
[ 0.03489015  3.75501532 -0.59502787 -0.58340114]
[ 2.01035278 -3.16717618 -0.02746437  0.83920809]
[ 2.69141263  0.61636617  0.46497376 -0.89819528]
--------------------------------------
| approxkl           | 1.7460687e-05 |
| clipfrac           | 0.0           |
| explained_variance | 9.18e-06      |
| fps                | 1945          |
| n_updates          | 209           |
| policy_entropy     | 0.72049415    |
| policy_loss        | 0.00077629765 |
| serial_timesteps   | 53504         |
| time_elapsed       | 34.3          |
| total_timesteps    | 53504         |
| value_loss         | 54

[ 1.59762455  3.28074392  0.25356234 -0.96928708]
[-1.77781591 -2.37315314 -0.79972587  0.85495305]
[-0.79314358  2.35531414  0.5982815   0.22099458]
[ 1.03330417  3.12171555  0.09017811 -0.29456429]
[-2.96004646 -1.81977027 -0.37477406 -0.40912309]
[-1.15424771  1.02660798 -0.04187289  0.40486705]
[-2.02717532  1.06856632 -0.40185024  0.05366495]
[ 0.90182116 -3.4571368   0.03175081  0.81828846]
[-0.4095532   3.86140514 -0.46391146  0.17022391]
[-1.87488834  3.86218553 -0.2372467   0.11651666]
[ 2.90315895 -3.15588128  0.62974246 -0.61961361]
---------------------------------------
| approxkl           | 0.00018941809  |
| clipfrac           | 0.0            |
| explained_variance | -3.22e-06      |
| fps                | 1676           |
| n_updates          | 217            |
| policy_entropy     | 0.7026551      |
| policy_loss        | -8.1060105e-05 |
| serial_timesteps   | 55552          |
| time_elapsed       | 35.5           |
| total_timesteps    | 55552          |
| value_lo

[ 3.3918162  -0.73385801  0.54926737  0.71315749]
[ 2.58816821  2.18315047  0.22569228 -0.25221709]
[ 0.44958956 -1.32036523  0.54434005  0.99537652]
[2.76212993 2.31244947 0.54759342 0.11535518]
[-1.66444704  3.77407475  0.96367306 -0.22601314]
[ 2.60249366 -2.88261171  0.67719322 -0.11448555]
[2.69867431 1.72197674 0.87495532 0.90549435]
[-3.35508976  2.78588932  0.21065296 -0.11171245]
[-0.60721465 -1.9314437  -0.33787459 -0.36300418]
[-3.73776225 -2.08543315 -0.39785854  0.3234706 ]
[ 1.59140049 -0.48253716 -0.24275396  0.71659344]
-------------------------------------
| approxkl           | 0.0010705531 |
| clipfrac           | 0.0          |
| explained_variance | -7.63e-06    |
| fps                | 1818         |
| n_updates          | 225          |
| policy_entropy     | 0.7031313    |
| policy_loss        | 0.008929663  |
| serial_timesteps   | 57600        |
| time_elapsed       | 36.7         |
| total_timesteps    | 57600        |
| value_loss         | 8612203.0    |
--

[ 2.28904763  2.2313201  -0.80896857 -0.08296284]
[-2.85599778  3.59432681  0.15332205  0.65844022]
[-0.90791937  3.27628781  0.81756016  0.56981683]
[-1.87371982  0.68116757  0.57146541 -0.14545496]
[ 1.75783032  3.57013783  0.19195972 -0.39646241]
[ 3.4101414   1.15174082  0.84537599 -0.86486366]
[-1.01988732  1.93448752 -0.20890851 -0.80631259]
[-0.25885815  0.87106011 -0.12143078  0.79577291]
[-2.69882972 -0.76329529 -0.71730573 -0.25034321]
[-2.20608588 -2.76927487  0.89822353 -0.67857538]
--------------------------------------
| approxkl           | 5.7461275e-05 |
| clipfrac           | 0.0           |
| explained_variance | -1.07e-06     |
| fps                | 1813          |
| n_updates          | 233           |
| policy_entropy     | 0.70215636    |
| policy_loss        | 0.0011887177  |
| serial_timesteps   | 59648         |
| time_elapsed       | 37.7          |
| total_timesteps    | 59648         |
| value_loss         | 6683239.0     |
--------------------------------

[ 2.41669072  3.30038779  0.01615862 -0.72606143]
[-0.28017214 -0.54071337 -0.8229843  -0.35823743]
[-3.57506089  3.73761488 -0.5274567   0.0135293 ]
[-0.22884883  0.7248503   0.47367637 -0.60659894]
[-0.08903334 -2.39528399 -0.70953376 -0.29866727]
[-0.44990508  3.56303896  0.78406792  0.21713626]
[ 1.36107656 -2.61387429  0.38282312 -0.63537078]
[-3.0107186  -1.55204468 -0.70570588 -0.21394772]
[-1.29058403 -0.54606265  0.85302179  0.13402705]
[-0.92283664 -2.49831375 -0.06578342  0.86417703]
-------------------------------------
| approxkl           | 0.0014487583 |
| clipfrac           | 0.0          |
| explained_variance | -7.87e-06    |
| fps                | 1939         |
| n_updates          | 241          |
| policy_entropy     | 0.6961636    |
| policy_loss        | 0.00816433   |
| serial_timesteps   | 61696        |
| time_elapsed       | 38.9         |
| total_timesteps    | 61696        |
| value_loss         | 4250030.5    |
-------------------------------------
[ 0.78

[-2.30476495  3.09623984 -0.76017692 -0.96077892]
[ 0.65469723  0.66158382 -0.26639012  0.163984  ]
[-0.09165205 -1.27093343 -0.25381077 -0.46617698]
[ 3.95655267 -0.50280317 -0.06634068 -0.95483916]
[3.767889   1.8356935  0.15140977 0.14206414]
[1.25474145 3.57677588 0.77158901 0.42789956]
[ 0.459582    2.65997467 -0.14287427 -0.19284462]
[ 2.80439792  2.88982954  0.43573332 -0.17630563]
[ 2.8203358  -1.72468006 -0.31933378  0.55984595]
[ 1.05351527  2.20631092 -0.83674451  0.10835788]
---------------------------------------
| approxkl           | 9.396515e-06   |
| clipfrac           | 0.0            |
| explained_variance | -5.25e-06      |
| fps                | 2031           |
| n_updates          | 249            |
| policy_entropy     | 0.6941632      |
| policy_loss        | -0.00021403155 |
| serial_timesteps   | 63744          |
| time_elapsed       | 40             |
| total_timesteps    | 63744          |
| value_loss         | 2488562.5      |
----------------------------

[ 1.76784373  2.04949552 -0.61836659  0.27811171]
[ 2.35377009 -3.51974672  0.78085817  0.90103793]
[-3.03884552  3.42092093  0.51744499 -0.71984337]
[-3.27543579  3.46499141  0.54565338  0.57253335]
[ 1.3560887  -2.14930355  0.17602208  0.03174934]
[ 0.37371389 -1.30063689 -0.23770111  0.10187519]
[-2.72161687  0.17988746  0.43028786  0.33930223]
[ 1.62382078 -1.82770235  0.14119453  0.4155403 ]
[-3.37851438 -1.19827363  0.31385396 -0.84854479]
[-0.91888349 -0.09076527  0.19123849 -0.09027574]
--------------------------------------
| approxkl           | 1.6308531e-05 |
| clipfrac           | 0.0           |
| explained_variance | 1.67e-06      |
| fps                | 1807          |
| n_updates          | 257           |
| policy_entropy     | 0.6935967     |
| policy_loss        | -0.000585915  |
| serial_timesteps   | 65792         |
| time_elapsed       | 41.2          |
| total_timesteps    | 65792         |
| value_loss         | 4644224.0     |
--------------------------------

[-1.14693008 -3.38457897  0.65463498  0.3323483 ]
[-0.49474335  0.94834169 -0.98330551 -0.04493498]
[ 3.77545813  2.86692515 -0.79794939 -0.67747423]
[ 3.1512062   2.48711412 -0.96279501  0.07519946]
[-2.05429439  2.89061688  0.17938466  0.83293461]
[-3.01045736 -2.08886521 -0.80232928  0.14923985]
[ 1.56895356e+00  3.52622827e+00  2.62077600e-03 -5.88310469e-01]
[-0.56657672  2.3634883   0.44302391  0.95824361]
[-3.86412344 -1.27816109 -0.88266494  0.83197639]
[ 3.57017399  2.50642412 -0.86090781  0.60062529]
-------------------------------------
| approxkl           | 0.0014890723 |
| clipfrac           | 0.0          |
| explained_variance | -1.72e-05    |
| fps                | 1781         |
| n_updates          | 265          |
| policy_entropy     | 0.69822246   |
| policy_loss        | 0.012785222  |
| serial_timesteps   | 67840        |
| time_elapsed       | 42.3         |
| total_timesteps    | 67840        |
| value_loss         | 7341350.5    |
----------------------------

[ 1.00181644  1.7296159   0.7984312  -0.8304675 ]
[-0.77871015 -0.27016168 -0.05164721 -0.18453517]
[-0.84792922  3.56867702  0.39203567 -0.04831374]
[-3.52265092  0.64084106  0.42808078  0.74678763]
[ 1.30685997 -0.16999654  0.88861136 -0.8090211 ]
[-2.29185632 -3.59527695 -0.44369276  0.03232609]
[-3.22745177 -0.56618524 -0.75077931  0.22889947]
[ 0.04274986 -1.90224117 -0.42762945 -0.29800433]
[-1.03698875 -0.88725708 -0.27675103 -0.63478344]
[ 2.98670129 -2.34977324  0.14090814  0.08922463]
-------------------------------------
| approxkl           | 0.0026730937 |
| clipfrac           | 0.0146484375 |
| explained_variance | 1.01e-06     |
| fps                | 1881         |
| n_updates          | 273          |
| policy_entropy     | 0.67863935   |
| policy_loss        | -0.015051718 |
| serial_timesteps   | 69888        |
| time_elapsed       | 43.4         |
| total_timesteps    | 69888        |
| value_loss         | 4130545.5    |
-------------------------------------
[-2.14

[-2.21054138 -2.49605702 -0.32034616 -0.36150848]
[-1.89547963  2.10264242 -0.65824212  0.55899552]
[-2.51934282  0.17981391  0.30063822 -0.86674792]
[ 1.85859457  0.72459689  0.84993147 -0.72770165]
[-3.42555224 -1.39895009 -0.91179269  0.18300024]
[-3.570991   -2.81808278 -0.04931541 -0.0499391 ]
[1.8431934  3.88739197 0.31306099 0.9664525 ]
[ 2.85852092 -1.88608409 -0.79930694 -0.19325123]
[-0.74978277  1.24168719  0.00217483  0.14862189]
[ 1.57556841 -1.86384137  0.07300006  0.94321253]
--------------------------------------
| approxkl           | 0.00047810155 |
| clipfrac           | 0.0           |
| explained_variance | -8.11e-06     |
| fps                | 1910          |
| n_updates          | 281           |
| policy_entropy     | 0.67625576    |
| policy_loss        | -0.0078437375 |
| serial_timesteps   | 71936         |
| time_elapsed       | 44.4          |
| total_timesteps    | 71936         |
| value_loss         | 4159082.5     |
------------------------------------

[ 3.25497748 -1.56041247  0.26816269  0.72321531]
[ 3.1618175   1.41219951  0.96737562 -0.38500208]
[ 0.34900848 -1.99669613 -0.04591651 -0.40552226]
[ 0.16983365 -0.36875105  0.40284102  0.43497641]
[-0.01060793  2.67981814 -0.38081719  0.72474389]
[-0.00817249  0.22742161  0.15706011  0.99321841]
[ 0.32283427  2.81933934 -0.68037456 -0.75024926]
[ 0.08853187 -2.40957023  0.47245043 -0.45315691]
[ 1.56426353 -3.57034175 -0.03669494  0.84204497]
[ 0.39704689 -0.05927088  0.57499512  0.6168906 ]
--------------------------------------
| approxkl           | 0.00026977522 |
| clipfrac           | 0.0           |
| explained_variance | 5.36e-07      |
| fps                | 1864          |
| n_updates          | 289           |
| policy_entropy     | 0.68969744    |
| policy_loss        | -0.0029624884 |
| serial_timesteps   | 73984         |
| time_elapsed       | 45.5          |
| total_timesteps    | 73984         |
| value_loss         | 6445139.0     |
--------------------------------

[-3.81817805  3.13935417  0.64361724 -0.47963486]
[-2.08185287 -1.41092231  0.61019165  0.56292749]
[ 2.11368343 -3.07562251  0.09869229  0.242846  ]
[-1.83389508  2.06780722 -0.41167781  0.79516922]
[-0.77928692  2.98465168  0.63987486 -0.87482946]
[ 2.76222771  1.14062178  0.95156045 -0.11946554]
[ 1.13154883  3.09295523 -0.4722459   0.45301804]
[-3.87752177  0.88561367  0.44068938 -0.98881154]
[ 0.02173309  3.099334    0.6541952  -0.4266974 ]
Episode 77	Average Score: -282590.26[-1.34044258  1.91241077 -0.02849376 -0.53404911]
[ 2.11792615  1.55246075 -0.33079412  0.84840293]
--------------------------------------
| approxkl           | 0.00034236436 |
| clipfrac           | 0.0           |
| explained_variance | -7.51e-06     |
| fps                | 1863          |
| n_updates          | 297           |
| policy_entropy     | 0.6936975     |
| policy_loss        | -0.0017382604 |
| serial_timesteps   | 76032         |
| time_elapsed       | 46.6          |
| total_timesteps    | 7

[-2.0093526   2.78997814  0.68200358  0.46158305]
[ 1.16548593  0.2682466  -0.56652574  0.41680809]
[ 0.70001043  1.9987531  -0.23904328 -0.1958456 ]
[ 1.69104721 -2.29565999 -0.69904507 -0.66240941]
[-2.33292525  3.03085315 -0.63594229 -0.65654242]
[ 2.54896361 -2.76846767  0.82820057 -0.62574323]
[-2.17511357 -2.1253505  -0.12469126  0.5445833 ]
[-1.8379944   2.38576433  0.18077613 -0.11340788]
Episode 79	Average Score: -281062.92[ 2.49559442 -3.21478586 -0.02052318  0.75038396]
[-0.2892922   2.301373    0.53533061 -0.74519156]
[ 1.84720965  3.57374073 -0.22443697  0.86439489]
[ 0.58406847  0.98672879 -0.57934726  0.9880888 ]
---------------------------------------
| approxkl           | 0.00022737206  |
| clipfrac           | 0.0            |
| explained_variance | 2.44e-06       |
| fps                | 1903           |
| n_updates          | 305            |
| policy_entropy     | 0.70247006     |
| policy_loss        | -0.00034561974 |
| serial_timesteps   | 78080          |
| ti

[ 0.22692157 -1.37571869 -0.59168797  0.79679714]
[-0.35689553  3.91826967 -0.03096244 -0.21450989]
[ 3.44813914  1.84740997 -0.04113997 -0.64464455]
[-0.58995969  2.97523715 -0.25028139 -0.21953424]
[ 0.00291028 -0.18534586  0.12183886 -0.34354815]
[-3.9080737  -1.61535148  0.43632424 -0.46666211]
Episode 81	Average Score: -280686.19[-1.91089545 -2.42783722 -0.46215407 -0.04005833]
[ 2.76429525 -3.62161689 -0.52299713  0.82052879]
[-3.3965166  -1.136998    0.23768819 -0.95230392]
[3.8592751  0.46876604 0.82411378 0.97817375]
[0.05374622 3.73319582 0.02231137 0.98304396]
[ 3.36540344 -2.34961292  0.59791481  0.84505578]
--------------------------------------
| approxkl           | 0.0007687002  |
| clipfrac           | 0.0           |
| explained_variance | 4.77e-07      |
| fps                | 1833          |
| n_updates          | 313           |
| policy_entropy     | 0.72026825    |
| policy_loss        | -0.0025610272 |
| serial_timesteps   | 80128         |
| time_elapsed       

[ 3.47958184 -2.79552404  0.90051725  0.93870268]
[ 1.09755782  2.40565168 -0.5393129  -0.31256107]
[1.69923476 2.99796493 0.51019114 0.77895058]
[ 3.60140432e+00  3.59893244e+00 -1.72504617e-02 -3.04502781e-03]
Episode 83	Average Score: -281722.23[-3.14818179  0.22316639 -0.70394389 -0.92592481]
[3.30052404 0.4473198  0.32465955 0.94574185]
[ 2.23527247  3.53158423  0.33259244 -0.40165882]
[ 1.62314163  1.67058703  0.04476205 -0.06477654]
[ 1.11507622  1.71971109 -0.031047    0.96586877]
[-0.5801967  -2.16596232 -0.77619342 -0.90730497]
[ 2.6119634  -0.26189035  0.52613659 -0.6811832 ]
[-2.70193854  2.92767633 -0.67118085 -0.33494274]
-------------------------------------
| approxkl           | 0.009822803  |
| clipfrac           | 0.12207031   |
| explained_variance | -1.31e-06    |
| fps                | 1871         |
| n_updates          | 321          |
| policy_entropy     | 0.7296267    |
| policy_loss        | -0.022130173 |
| serial_timesteps   | 82176        |
| time_elapsed

[ 2.92849991  1.35461439 -0.9448686  -0.48250018]
[-2.45937383  1.66694612 -0.67056806 -0.16144685]
Episode 85	Average Score: -282185.24[-3.46036134  1.83057889  0.96064504 -0.41066868]
[ 1.89484644 -0.41879331  0.3896195   0.90713587]
[ 2.58605422  3.38723194 -0.85003574  0.65491317]
[-3.03635498  0.96398031 -0.88012358 -0.94969386]
[ 3.17135654 -3.95403383  0.85104702  0.4336941 ]
[ 1.52257723  1.79751156 -0.01620565  0.97412079]
[ 0.50667242  3.88428089 -0.43975248  0.54224418]
[ 3.90853148 -2.20271939  0.49505961  0.8657045 ]
[2.33564733 3.76096762 0.93720276 0.81676263]
-------------------------------------
| approxkl           | 0.004340479  |
| clipfrac           | 0.05859375   |
| explained_variance | -8.34e-07    |
| fps                | 1751         |
| n_updates          | 329          |
| policy_entropy     | 0.72106934   |
| policy_loss        | -0.010156784 |
| serial_timesteps   | 84224        |
| time_elapsed       | 51           |
| total_timesteps    | 84224        |


[ 3.41385339  2.74865426 -0.39482006  0.07947832]
[-2.88921993  1.43315493  0.06698159 -0.14151345]
[ 3.53458884  1.30568212  0.4677884  -0.32510217]
[ 1.40468374 -3.53705333 -0.77149701 -0.30023471]
[ 3.36420393 -3.41116356 -0.71959063 -0.52512083]
[ 2.57655658 -2.96779925 -0.02117527 -0.17421005]
[-1.96870863  1.50625168  0.55799412  0.34369362]
[ 1.47070343  0.34510475  0.47073713 -0.53876423]
[ 1.96731664  2.23206603 -0.65019504 -0.30675684]
[-1.96726104 -2.06637044 -0.97786904  0.78902429]
--------------------------------------
| approxkl           | 0.00021889037 |
| clipfrac           | 0.0           |
| explained_variance | 1.79e-07      |
| fps                | 2005          |
| n_updates          | 337           |
| policy_entropy     | 0.7437102     |
| policy_loss        | -0.0018126105 |
| serial_timesteps   | 86272         |
| time_elapsed       | 52            |
| total_timesteps    | 86272         |
| value_loss         | 19048316.0    |
--------------------------------

[-3.14814765  1.48755913  0.85859983 -0.99771575]
[ 1.11891892 -3.42017035 -0.36641082 -0.35581532]
[-0.77975409 -1.22282426 -0.63829581 -0.63104269]
[-0.39682907  1.19895529 -0.78651058 -0.96987115]
[-2.52905874 -3.03248406  0.03015792 -0.22851563]
[-0.29858065  2.90571009 -0.63543444 -0.92611848]
[ 1.51574885  3.05353356 -0.39585014  0.64110354]
[2.7058637  3.49345568 0.19516564 0.39404266]
[ 2.77726159 -0.24633217  0.78531065 -0.88181072]
[-3.53182427 -3.87832076  0.93807571 -0.69335096]
-------------------------------------
| approxkl           | 0.0023376471 |
| clipfrac           | 0.0          |
| explained_variance | 1.25e-06     |
| fps                | 1891         |
| n_updates          | 345          |
| policy_entropy     | 0.7491067    |
| policy_loss        | 0.015098698  |
| serial_timesteps   | 88320        |
| time_elapsed       | 53.2         |
| total_timesteps    | 88320        |
| value_loss         | 9942128.0    |
-------------------------------------
[-0.148748

[ 3.5234736  -3.18567857  0.76411763 -0.63092999]
[-3.04876262  2.90235154 -0.72175963 -0.51809896]
[ 1.73745487  0.44926952  0.98491214 -0.40521617]
[ 0.76666387 -3.1906615  -0.5244687  -0.01646556]
[2.97817098 3.18775486 0.91438061 0.55891147]
[ 1.89283363  2.97349513  0.69936361 -0.07334644]
[0.71661344 0.56779906 0.57014915 0.17675919]
[ 0.98947058  2.24252212 -0.1664899  -0.54650683]
[-2.04391236  2.9917077   0.9062711   0.14259138]
[ 1.15416969  0.74276372  0.36653295 -0.79511216]
--------------------------------------
| approxkl           | 0.00033305906 |
| clipfrac           | 0.0           |
| explained_variance | -3.58e-07     |
| fps                | 2033          |
| n_updates          | 353           |
| policy_entropy     | 0.7593324     |
| policy_loss        | 0.00029848318 |
| serial_timesteps   | 90368         |
| time_elapsed       | 54.2          |
| total_timesteps    | 90368         |
| value_loss         | 8901581.0     |
--------------------------------------
[

[ 3.91220494  1.61116838 -0.50087505 -0.06380091]
[-2.77366936  3.50069945  0.63735599  0.37131338]
[ 1.32592681 -1.58800106  0.48367967 -0.21550245]
[ 0.64093645 -2.07056794  0.15588928 -0.40512086]
[-1.4535545  -1.71556032 -0.5985458   0.84929867]
[ 0.34915498 -1.81808649  0.19213318  0.86898872]
[ 0.19371055 -3.96947793  0.66669701  0.78125324]
[-0.5916517  -3.46603582  0.61177228  0.56058886]
[ 1.93920479 -0.16026529 -0.78036502 -0.1842139 ]
[-3.38191565 -0.06666626  0.92929934 -0.95490509]
-------------------------------------
| approxkl           | 0.012490756  |
| clipfrac           | 0.20703125   |
| explained_variance | 8.11e-06     |
| fps                | 1971         |
| n_updates          | 361          |
| policy_entropy     | 0.76297057   |
| policy_loss        | -0.009814738 |
| serial_timesteps   | 92416        |
| time_elapsed       | 55.3         |
| total_timesteps    | 92416        |
| value_loss         | 3583126.5    |
-------------------------------------
[-1.94

[-2.8989164  -0.73106295 -0.77486644 -0.12903736]
[-2.0101122  -1.7765807   0.44882926 -0.98505561]
[ 1.23019757 -0.46975846  0.35738118 -0.61774831]
[-2.22625224 -3.1087322   0.79037235  0.14124025]
[-1.25978232 -0.13417088  0.05562951 -0.51032693]
[ 0.59292494  0.22798195 -0.10501954 -0.41202502]
[1.57215323 0.07089557 0.42947356 0.27036815]
[ 0.54404018 -1.36686324  0.98742792  0.95434537]
[-1.92348169 -0.689962    0.67108916 -0.6856787 ]
[ 2.61708941 -2.80511615  0.29134158 -0.31391767]
--------------------------------------
| approxkl           | 7.5625096e-05 |
| clipfrac           | 0.0           |
| explained_variance | -8.34e-07     |
| fps                | 1716          |
| n_updates          | 369           |
| policy_entropy     | 0.74987775    |
| policy_loss        | 0.00026386062 |
| serial_timesteps   | 94464         |
| time_elapsed       | 56.4          |
| total_timesteps    | 94464         |
| value_loss         | 5153001.5     |
------------------------------------

[ 1.68416985 -3.89004194  0.3930678   0.45263161]
[ 1.62214947  0.41397085 -0.03512812  0.00758931]
[-1.92548842 -0.47748089  0.45997745  0.28102335]
[ 1.98405388  0.17746598 -0.25293811  0.08832323]
[ 2.67775525 -0.42744793  0.22959386 -0.97817724]
[-3.19309722 -2.4279495  -0.12007004 -0.66089222]
[-3.00735178  2.20655076 -0.11542847  0.47189634]
[-0.35971389  0.48743363  0.68833147 -0.98495571]
[ 2.9274488  -0.38703284  0.42861007  0.25522205]
[ 3.12471152 -2.95995317 -0.45604774  0.46934196]
-------------------------------------
| approxkl           | 8.306484e-05 |
| clipfrac           | 0.0          |
| explained_variance | -9.54e-07    |
| fps                | 1814         |
| n_updates          | 377          |
| policy_entropy     | 0.7387926    |
| policy_loss        | 0.001736466  |
| serial_timesteps   | 96512        |
| time_elapsed       | 57.6         |
| total_timesteps    | 96512        |
| value_loss         | 7646633.0    |
-------------------------------------
[ 0.84

[ 3.3623067   0.86813243 -0.33033004  0.26105651]
[-1.79610661  1.69609681  0.551854   -0.41716295]
[ 1.1022404   0.95171775  0.82623257 -0.5842745 ]
[ 3.80560169 -1.97552025 -0.69285751  0.80371053]
[ 0.4383769  -0.20827836  0.3912564  -0.39266433]
[-1.19191019 -0.27207333 -0.99552163 -0.83904746]
[-0.7541788  -1.55631719  0.05414347  0.13787822]
[ 3.76264055 -3.32751135 -0.76618828 -0.36562442]
[-3.68384564  1.53550024  0.94576352  0.24125867]
[-2.60247915 -3.4439799   0.85211825  0.89413447]
-------------------------------------
| approxkl           | 0.0006536417 |
| clipfrac           | 0.0          |
| explained_variance | 1.91e-06     |
| fps                | 1856         |
| n_updates          | 385          |
| policy_entropy     | 0.7323717    |
| policy_loss        | 0.0037647176 |
| serial_timesteps   | 98560        |
| time_elapsed       | 58.7         |
| total_timesteps    | 98560        |
| value_loss         | 8461940.0    |
-------------------------------------
[-2.54

[ 2.07279669 -2.25342833  0.23109994 -0.74528359]
[-3.73463479 -2.85093748  0.84953518  0.60964478]
[ 3.15433216  1.9173628   0.30469219 -0.7467347 ]
[3.95429156 0.40012504 0.41864921 0.08709458]
[ 0.38398983  2.30818923  0.23190052 -0.66053387]
[-2.0086326  -0.28840172  0.91495412  0.74400801]
[ 0.29186642 -3.08878115 -0.76740823  0.12983605]
[-2.09347531  0.63967185  0.19286125 -0.04032794]
[-1.10021943  3.03713108 -0.69760355 -0.85716768]
[-1.40988164  1.33560473  0.75749186 -0.36174368]
-------------------------------------
| approxkl           | 0.0030276524 |
| clipfrac           | 0.0          |
| explained_variance | 3.22e-06     |
| fps                | 2018         |
| n_updates          | 393          |
| policy_entropy     | 0.73605776   |
| policy_loss        | 0.011755344  |
| serial_timesteps   | 100608       |
| time_elapsed       | 59.7         |
| total_timesteps    | 100608       |
| value_loss         | 3327399.5    |
-------------------------------------
[ 2.436805

[-1.01342928 -1.20318292  0.57909952 -0.08283856]
[ 1.23605815 -2.15022462  0.27000172  0.86639777]
[ 3.67569486 -0.30392486 -0.36763988 -0.84507527]
[ 1.33032089 -0.47645539  0.29822609  0.86480066]
[-2.11824256  2.7905606  -0.56866639  0.00772135]
[ 1.88098351  0.01718601 -0.76545108 -0.43345977]
[-1.70149456 -0.05047773 -0.51494468  0.95127113]
[ 0.00600183 -1.59305849 -0.71433679  0.61563073]
-------------------------------------
| approxkl           | 0.016053619  |
| clipfrac           | 0.17773438   |
| explained_variance | -9.54e-07    |
| fps                | 2026         |
| n_updates          | 401          |
| policy_entropy     | 0.88493925   |
| policy_loss        | -0.011232359 |
| serial_timesteps   | 102656       |
| time_elapsed       | 60.8         |
| total_timesteps    | 102656       |
| value_loss         | 19524972.0   |
-------------------------------------
[-3.45269588 -2.99625606  0.51977282  0.96415501]
[ 0.2428022  -1.78425709 -0.13517728  0.74279266]
[-2.76

[-2.30669752 -3.12736081 -0.85691109 -0.76063711]
[ 2.13701229 -1.75837996 -0.88018802  0.8553438 ]
[-3.20348882 -1.43514899 -0.03745786  0.2228966 ]
[ 3.01939742 -3.19258487 -0.79959408  0.13664531]
[-3.98793953 -0.09229358 -0.70906478  0.37574627]
--------------------------------------
| approxkl           | 0.00010845818 |
| clipfrac           | 0.0           |
| explained_variance | 7.15e-07      |
| fps                | 1732          |
| n_updates          | 409           |
| policy_entropy     | 0.8893819     |
| policy_loss        | 0.00023189845 |
| serial_timesteps   | 104704        |
| time_elapsed       | 61.9          |
| total_timesteps    | 104704        |
| value_loss         | 15271204.0    |
--------------------------------------
[-3.3524325  -1.7172712   0.7863355   0.83565071]
[ 1.39679672 -2.77343986  0.15063103  0.39598397]
[-2.09725834  2.33185828 -0.03085456 -0.57421797]
[ 3.83634179  3.2683747  -0.21980375 -0.26985958]
[-3.84629339  3.92392881 -0.5778783  -0.113

[-0.91715536 -1.14993414  0.62358264 -0.96230325]
[-2.8630926  -1.27798682  0.82579966  0.34606277]
[3.97979582 3.21522747 0.74684067 0.38640525]
[-3.82553862 -1.69051457 -0.07592758 -0.82850186]
[-2.6050594   3.20583521 -0.76246948  0.01627504]
[-3.52058348 -1.85611365 -0.67243072  0.65526525]
[-0.56377143 -3.9842857  -0.40188392  0.05770268]
--------------------------------------
| approxkl           | 4.5751774e-05 |
| clipfrac           | 0.0           |
| explained_variance | -4.05e-06     |
| fps                | 1947          |
| n_updates          | 417           |
| policy_entropy     | 0.85020787    |
| policy_loss        | 0.0011498205  |
| serial_timesteps   | 106752        |
| time_elapsed       | 62.9          |
| total_timesteps    | 106752        |
| value_loss         | 9369210.0     |
--------------------------------------
[ 2.66105779 -1.24855357  0.28616452 -0.65156733]
[ 2.48636611 -3.210293    0.43561257 -0.67125166]
[-2.89220855 -0.53409135 -0.08652474  0.8096516

[-0.9856127   1.68876735 -0.38947523 -0.86913308]
[ 2.37743585  0.99126731 -0.67535331 -0.10476512]
[ 1.04489606 -2.45133137  0.11070334 -0.87963486]
[ 0.39670323  3.17672107 -0.84905932  0.0102072 ]
[-3.5125482   1.74988214 -0.65712702 -0.74768263]
[-1.01603098 -3.99026106  0.44184661 -0.52866365]
[ 2.08044892  0.77544044  0.4913875  -0.5458022 ]
[-0.8393783  -1.7237295  -0.62023693 -0.28090598]
[ 1.79682986  2.28844352 -0.96687361 -0.95554723]
---------------------------------------
| approxkl           | 2.032167e-05   |
| clipfrac           | 0.0            |
| explained_variance | 2.21e-06       |
| fps                | 2017           |
| n_updates          | 425            |
| policy_entropy     | 0.8394202      |
| policy_loss        | -5.9447775e-05 |
| serial_timesteps   | 108800         |
| time_elapsed       | 64             |
| total_timesteps    | 108800         |
| value_loss         | 5924849.0      |
---------------------------------------
[ 3.04495281 -1.71050523 -0.03

KeyboardInterrupt: 